name: Build & Deploy Flutter Web to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Empêche les déploiements concurrents
concurrency:
  group: pages
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.2"
          channel: stable
          cache: true

      - name: Flutter pub get
        run: flutter pub get

      - name: Build Flutter Web (release, base at root)
        run: flutter build web --release --base-href=/

      # SPA fallback : GitHub Pages sert 404.html sur routes profondes
      - name: Add SPA fallback (404.html)
        run: cp build/web/index.html build/web/404.html

      # Attache automatiquement ton domaine perso
      - name: Add CNAME for custom domain
        run: echo "www.golieux.com" > build/web/CNAME

      # (Optionnel) Si tu veux forcer des chemins relatifs, décommente ces lignes :
      # - name: Post-process index.html (relative paths)
      #   run: |
      #     sed -i 's|href="manifest.json"|href="./manifest.json"|g' build/web/index.html
      #     sed -i 's|src="flutter_bootstrap.js"|src="./flutter_bootstrap.js"|g' build/web/index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4